### PR TITLE
Adding laravel 9 support

### PR DESCRIPTION
**Pull request by nicko170**

### CODE REVIEW

**Comment by apsbd** [comment]
Please, approve this pull-request. It'll be very helpful. Thanks

**Comment by PimButton** [comment]
@atymic can you take a look at this PR? Support for Laravel 9 would be great!

**Comment by chieft3ch** [comment]
Please approve this request. We are also waiting on this. Thanks!a

**Comment by nicko170** [comment]
This repo was never set up properly when I created it, and I never got the access that I thought I should have :-(

@atymic can you please approve.

**Comment by atymic** [comment]
@nicko170 sent you an admin invite.

**Comment by nicko170** [comment]
@t3chbits v1.1.0 is tagged. Should be good to go :-)

**Comment by chieft3ch** [comment]
Ah this is amazing, thank you!

**Comment by PimButton** [comment]
Perfect, thanks!

**Pull request merged**
