### PR TITLE
Use opinionated Pint

### PR DESCRIPTION
**Pull request by dwightwatson**
This removes the `pint.json` configuration file to use the default settings.

### CODE REVIEW

**Comment by dwightwatson** [comment]
@mabdullahsari happy with this change?

If you're good then we can tag a `2.x` version to properly release this.

**Comment by mabdullahsari** [comment]
@dwightwatson 

Yup! This is definitely the way to go in a collaborative repository like this. It's my bad that I forgot the remove the customized configuration file! 🙌

**Comment by dwightwatson** [comment]
Sweet, all good. 

Would you like to do the honours of tagging 2.x and doing a release? Otherwise I can take a look tomorrow.

**Comment by mabdullahsari** [comment]
Sure thing!

**Pull request merged**
