### PR TITLE
Channel revamp

### PR DESCRIPTION
**Pull request by mabdullahsari**
This PR carries over the code [from this repository](https://github.com/dive-be/laravel-expo-channel), completely replacing the current logic.

Things that I have done in preparation for a v2 release in this repository:

- [x] Removed all company references and replaced them with `laravel-notification-channels/expo`
- [x] Removed a few dependencies that were not necessary, to improve stability.
- [x] Revised all files and fixed typos.

Currently, only PHP 8.3 and Laravel 11 are supported. Should this channel support older versions? If yes, then we'll have to get rid of useful attributes such as `#[SensitiveParameter]` which is not available in older PHP versions. Since this is going to justify a new major release, I'm the proponent of keeping it this way! 🙌 I haven't added scuritinizer and the other stuff because Pint, Larastan is included.

You are most definitely welcome to suggest changes, and I'll try my best to implement them asap!

### CODE REVIEW

**Comment by dwightwatson** [comment]
This is fantastic, thanks for going to the effort to merge your work into this collection. All for dropping previous PHP/Laravel versions and going future-only.

I wonder if we should just go with default Pint settings rather than customising.

StyleCI is enabled on this repo too (and probably be a pain to get it removed) so we may just have to appease it.

I've branched off the previous code to `1.x` so it's still available separately if required.

**Comment by atymic** [comment]
If you'd like me to remove styleci I can

**Comment by dwightwatson** [comment]
Yes - could we please remove StyleCI. It doesn't seem to vibe with Pint.

**Comment by mabdullahsari** [comment]
@atymic Yes please. Let's get rid of StyleCI and use Pint instead.

**Pull request merged**
